# Generated by Django 5.1.6 on 2025-02-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='rooms', to='base.tag'),
        ),
    ]
