# Generated by Django 5.1.3 on 2025-01-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag_room_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.tag'),
        ),
    ]
