# Generated by Django 5.1.6 on 2025-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='roomchatindividual',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
