# Generated by Django 5.1.6 on 2025-03-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_tags_alter_roomchatindividual_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomchatindividual',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
