# Generated by Django 5.1.3 on 2025-01-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members_count',
            field=models.ManyToManyField(related_name='member_count', to='base.customuser'),
        ),
    ]
