# Generated by Django 5.1.3 on 2025-01-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_chatbox_user_alter_studymaterials_upload_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myuploads', to='base.room'),
        ),
    ]
