# Generated by Django 5.1.3 on 2025-01-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_userprofile_following_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='base.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rooms',
            field=models.ManyToManyField(related_name='profile-rooms+', to='base.room'),
        ),
    ]
