# Generated by Django 5.1.3 on 2025-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_userprofile_followers_alter_userprofile_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='assets/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
