# Generated by Django 5.1.6 on 2025-02-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='study_materials',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.AddField(
            model_name='folder',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='base.room'),
        ),
        migrations.AddField(
            model_name='studymaterials',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='base.folder'),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myuploads', to='base.room'),
        ),
    ]
