# Generated by Django 5.1.6 on 2025-02-24 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_chatbox_content_remove_chatbox_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatboxmembership',
            old_name='user',
            new_name='message_by',
        ),
        migrations.AddField(
            model_name='chatbox',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupcreation', to=settings.AUTH_USER_MODEL),
        ),
    ]
