# Generated by Django 5.1.6 on 2025-02-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_user_chatboxmembership_message_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatboxmembership',
            old_name='chatbox',
            new_name='chat_box',
        ),
    ]
